import type { TargetCountry } from "./job-sources";

export type GraduateProgramStatus = "open" | "opening_soon" | "watch";

export type GraduateProgram = {
  id: string;
  company: string;
  country: Extract<TargetCountry, "英国" | "加拿大">;
  title: string;
  location: string;
  cycle: string;
  status: GraduateProgramStatus;
  opensOn?: string;
  deadline?: string;
  url: string;
  evidence: string;
  fit: string;
  workAuthorization: string;
  verifiedAt: string;
};

// Every status below is backed by a dated official programme or vacancy page.
// Runtime labels downgrade expired dates to “待复核” instead of assuming a role remains open.
export const graduatePrograms: GraduateProgram[] = [
  {
    id: "barclays-banking-2027",
    company: "Barclays",
    country: "英国",
    title: "Banking Graduate Programme 2027",
    location: "London",
    cycle: "2027 intake",
    status: "open",
    url: "https://search.jobs.barclays/en/job/london/banking-graduate-programme-2027-london/13015/99885319536",
    evidence: "官方岗位 2026-08-29 上线，页面可直接申请",
    fit: "Banking · Strategy · Client Solutions",
    workAuthorization: "岗位页说明部分录用可评估 Skilled Worker，仍以具体资格审核为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "shell-uk-2027",
    company: "Shell",
    country: "英国",
    title: "Shell Graduate Programme 2027",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-01",
    url: "https://www.shell.co.uk/about-us/careers/shell-graduate-programme.html",
    evidence: "官方页面明确写明 2026 年 9 月开放",
    fit: "Commercial · Operations · Energy",
    workAuthorization: "官网要求申请人居住在英国；签证资格需在具体岗位核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deutsche-bank-uk-2027",
    company: "Deutsche Bank",
    country: "英国",
    title: "2027 Graduate Programme",
    location: "London / Birmingham",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-07",
    deadline: "2026-10-18",
    url: "https://careers.db.com/students-graduates/your-application/",
    evidence: "官方时间表：不同业务 9 月 7 日或 10 月 5 日开放",
    fit: "Consulting · Risk · Banking · Technology",
    workAuthorization: "须满足英国工作法规与具体岗位签证要求",
    verifiedAt: "2026-09-01",
  },
  {
    id: "zurich-uk-2027",
    company: "Zurich Insurance",
    country: "英国",
    title: "Graduate Schemes 2027",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-14",
    deadline: "2026-10-18",
    url: "https://www.zurich.co.uk/careers/graduate-schemes",
    evidence: "官方页面公布 9 月 14 日至 10 月 18 日申请窗口",
    fit: "Operations · Data · Insurance · Finance",
    workAuthorization: "签证与工作权利需在各项目职位页核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "baillie-gifford-2027",
    company: "Baillie Gifford",
    country: "英国",
    title: "Investment Research Graduate Programme",
    location: "Edinburgh",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-15",
    url: "https://www.bailliegifford.com/en/uk/individual-investors/careers/early-careers/graduate-programmes/",
    evidence: "官方页面明确写明 9 月 15 日开放；Technology 2027 不开放",
    fit: "Research · Analysis · Investment",
    workAuthorization: "工作权利与支持政策以申请页为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "natwest-economic-crime-2027",
    company: "NatWest Group",
    country: "英国",
    title: "Economic Crime Graduate Programme",
    location: "United Kingdom",
    cycle: "September 2027",
    status: "watch",
    url: "https://jobs.natwestgroup.com/pages/economic-crime-graduate-programmes",
    evidence: "2027 项目页已上线，官网提示加入 Early Talent Community 等待开放",
    fit: "Risk · Fraud · Data · Operations",
    workAuthorization: "具体项目可能要求 2027 年在英国具备工作权利",
    verifiedAt: "2026-09-01",
  },
  {
    id: "pwc-uk-advisory-2027",
    company: "PwC UK",
    country: "英国",
    title: "Advisory & Consulting Graduate 2027",
    location: "United Kingdom",
    cycle: "September 2027",
    status: "watch",
    url: "https://www.pwc.co.uk/careers/early-careers/graduate/advisory-consulting.html",
    evidence: "官方 2027 项目页已上线，需继续核验具体 vacancy",
    fit: "Consulting · Deals · Transformation",
    workAuthorization: "录用以持续具备英国工作权利为前提，担保看具体岗位",
    verifiedAt: "2026-09-01",
  },
  {
    id: "ey-uk-2027",
    company: "EY UK",
    country: "英国",
    title: "Graduate Programmes 2027",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "watch",
    url: "https://www.ey.com/en_uk/careers/students/graduates",
    evidence: "官方说明 2026 已关闭、将在 2026 年稍晚重新开放",
    fit: "Consulting · Assurance · Tax · Strategy",
    workAuthorization: "仅部分 Graduate vacancy 支持担保，必须逐条查看",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-customer-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Technology & Transformation — Customer New Grad 2027",
    location: "Toronto / Calgary / Halifax / Montréal / Vancouver",
    cycle: "Fall 2027",
    status: "open",
    deadline: "2026-09-18",
    url: "https://careers.deloitte.ca/job/Toronto%2C-ON-Technology-%26-Transformation-Customer-New-Grad-2027-Multiple-Locations-ON-M5H-0A9/134466-en_US/",
    evidence: "官方岗位 2026-08-20 上线，2026-09-18 截止",
    fit: "Customer · Product · Marketing · Commerce",
    workAuthorization: "岗位要求在加拿大合法工作；未承诺移民或工签支持",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-deals-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Deal Transformation & Post Merger Integration New Grad",
    location: "Toronto / Montréal / Calgary / Vancouver",
    cycle: "Winter / Fall 2027",
    status: "open",
    deadline: "2026-09-18",
    url: "https://careers.deloitte.ca/job/Toronto%2C-ON-AnalystConsultant%2C-Deal-Transformation-%26-Post-Merger-Integration-New-Grad-2027-Multiple-Locations-ON-M5H-0A9/134482-en_US/",
    evidence: "官方岗位 2026-08-19 上线，2026-09-18 截止",
    fit: "Strategy · Operations · Transformation",
    workAuthorization: "岗位要求满足加拿大工作资格；魁北克岗位有语言条件",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-tax-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Tax Analyst — New Grad 2027",
    location: "Multiple Canadian cities",
    cycle: "2027 intake",
    status: "open",
    deadline: "2026-09-13",
    url: "https://careers.deloitte.ca/job/Tax-%26-Legal-Tax-Analyst-New-Grad-2027-Multiple-Locations/134593-en_US/",
    evidence: "官方岗位 2026-08-17 上线；各地区 9 月 13 日至 10 月 4 日截止",
    fit: "Tax · Finance · Analysis",
    workAuthorization: "需满足加拿大工作资格并核验 CPA 先修要求",
    verifiedAt: "2026-09-01",
  },
  {
    id: "scotiabank-ib-vancouver-2027",
    company: "Scotiabank",
    country: "加拿大",
    title: "Investment Banking Analyst — New Grad",
    location: "Vancouver",
    cycle: "August 2027 start",
    status: "open",
    url: "https://jobs.scotiabank.com/job/Vancouver-GBM-Investment-Banking-Analyst-%28Vancouver%29-New-Grad-BC/604770517/",
    evidence: "官方 New Grad 岗位页在线，要求 2027 年春季前完成学位",
    fit: "Investment Banking · Finance · Research",
    workAuthorization: "加拿大工作资格与具体筛选条件以申请页为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "trafigura-calgary-2027",
    company: "Trafigura",
    country: "加拿大",
    title: "Calgary Development Graduate Programme",
    location: "Calgary",
    cycle: "October 2027 start",
    status: "open",
    deadline: "2026-09-21",
    url: "https://trafigura.wd3.myworkdayjobs.com/en-US/TrafiguraCareerSite/job/Calgary-Canada/Calgary-Development-Graduate-Programme_R-018524",
    evidence: "官方 Workday 岗位显示 2026-09-21 截止",
    fit: "Operations · Risk · Supply Chain",
    workAuthorization: "项目强调全球流动性；工作许可仍需向雇主确认",
    verifiedAt: "2026-09-01",
  },
  {
    id: "rogers-cpa-2027",
    company: "Rogers Communications",
    country: "加拿大",
    title: "CPA Rotational Program — Financial Analyst",
    location: "Toronto",
    cycle: "September 2027 start",
    status: "open",
    url: "https://jobs.rogers.com/job/Toronto-Financial-Analyst-ON/1417798200/",
    evidence: "官方岗位页已上线，明确为 2027 CPA Rotational Program",
    fit: "Finance · Analysis · Rotational",
    workAuthorization: "申请需提交大学成绩单；工作资格看岗位申请表",
    verifiedAt: "2026-09-01",
  },
  {
    id: "rbc-rotational-programs",
    company: "RBC",
    country: "加拿大",
    title: "New Graduate & Rotational Programs",
    location: "Canada",
    cycle: "Rolling cohorts",
    status: "watch",
    url: "https://jobs.rbc.com/ca/en/students-graduates-new-graduate-rotational-programs/",
    evidence: "官方项目集合页在线，包含 Capital Markets、CPA、Analyst 等路径",
    fit: "Banking · Finance · Technology · Leadership",
    workAuthorization: "各项目资格不同，必须在具体 vacancy 核验",
    verifiedAt: "2026-09-01",
  },
];
