import type { TargetCountry } from "./job-sources";

export type GraduateProgramStatus = "open" | "opening_soon" | "watch";

export type GraduateProgram = {
  id: string;
  company: string;
  country: Extract<TargetCountry, "英国" | "加拿大">;
  title: string;
  location: string;
  cycle: string;
  status: GraduateProgramStatus;
  opensOn?: string;
  deadline?: string;
  url: string;
  evidence: string;
  fit: string;
  workAuthorization: string;
  verifiedAt: string;
};

// Every status below is backed by a dated official programme or vacancy page.
// Runtime labels downgrade expired dates to “待复核” instead of assuming a role remains open.
export const graduatePrograms: GraduateProgram[] = [
  {
    id: "barclays-banking-2027",
    company: "Barclays",
    country: "英国",
    title: "Banking Graduate Programme 2027",
    location: "London",
    cycle: "2027 intake",
    status: "open",
    url: "https://search.jobs.barclays/en/job/london/banking-graduate-programme-2027-london/13015/99885319536",
    evidence: "官方岗位 2026-08-29 上线，页面可直接申请",
    fit: "Banking · Strategy · Client Solutions",
    workAuthorization: "岗位页说明部分录用可评估 Skilled Worker，仍以具体资格审核为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "shell-uk-2027",
    company: "Shell",
    country: "英国",
    title: "Shell Graduate Programme 2027",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-01",
    url: "https://www.shell.co.uk/about-us/careers/shell-graduate-programme.html",
    evidence: "官方页面明确写明 2026 年 9 月开放",
    fit: "Commercial · Operations · Energy",
    workAuthorization: "官网要求申请人居住在英国；签证资格需在具体岗位核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deutsche-bank-uk-2027",
    company: "Deutsche Bank",
    country: "英国",
    title: "2027 Graduate Programme",
    location: "London / Birmingham",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-07",
    deadline: "2026-10-18",
    url: "https://careers.db.com/students-graduates/your-application/",
    evidence: "官方时间表：不同业务 9 月 7 日或 10 月 5 日开放",
    fit: "Consulting · Risk · Banking · Technology",
    workAuthorization: "须满足英国工作法规与具体岗位签证要求",
    verifiedAt: "2026-09-01",
  },
  {
    id: "zurich-uk-2027",
    company: "Zurich Insurance",
    country: "英国",
    title: "Graduate Schemes 2027",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-14",
    deadline: "2026-10-18",
    url: "https://www.zurich.co.uk/careers/graduate-schemes",
    evidence: "官方页面公布 9 月 14 日至 10 月 18 日申请窗口",
    fit: "Operations · Data · Insurance · Finance",
    workAuthorization: "签证与工作权利需在各项目职位页核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "baillie-gifford-2027",
    company: "Baillie Gifford",
    country: "英国",
    title: "Investment Research Graduate Programme",
    location: "Edinburgh",
    cycle: "2027 intake",
    status: "opening_soon",
    opensOn: "2026-09-15",
    url: "https://www.bailliegifford.com/en/uk/individual-investors/careers/early-careers/graduate-programmes/",
    evidence: "官方页面明确写明 9 月 15 日开放；Technology 2027 不开放",
    fit: "Research · Analysis · Investment",
    workAuthorization: "工作权利与支持政策以申请页为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "natwest-economic-crime-2027",
    company: "NatWest Group",
    country: "英国",
    title: "Economic Crime Graduate Programme",
    location: "United Kingdom",
    cycle: "September 2027",
    status: "watch",
    url: "https://jobs.natwestgroup.com/pages/economic-crime-graduate-programmes",
    evidence: "2027 项目页已上线，官网提示加入 Early Talent Community 等待开放",
    fit: "Risk · Fraud · Data · Operations",
    workAuthorization: "具体项目可能要求 2027 年在英国具备工作权利",
    verifiedAt: "2026-09-01",
  },
  {
    id: "pwc-uk-advisory-2027",
    company: "PwC UK",
    country: "英国",
    title: "Advisory & Consulting Graduate 2027",
    location: "United Kingdom",
    cycle: "September 2027",
    status: "watch",
    url: "https://www.pwc.co.uk/careers/early-careers/graduate/advisory-consulting.html",
    evidence: "官方 2027 项目页已上线，需继续核验具体 vacancy",
    fit: "Consulting · Deals · Transformation",
    workAuthorization: "录用以持续具备英国工作权利为前提，担保看具体岗位",
    verifiedAt: "2026-09-01",
  },
  {
    id: "ey-uk-2027",
    company: "EY UK",
    country: "英国",
    title: "Graduate Programmes 2027",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "watch",
    url: "https://www.ey.com/en_uk/careers/students/graduates",
    evidence: "官方说明 2026 已关闭、将在 2026 年稍晚重新开放",
    fit: "Consulting · Assurance · Tax · Strategy",
    workAuthorization: "仅部分 Graduate vacancy 支持担保，必须逐条查看",
    verifiedAt: "2026-09-01",
  },
  {
    id: "bt-uk-2027",
    company: "BT Group",
    country: "英国",
    title: "Graduates & Apprenticeships 2027 — Register Interest",
    location: "UK-wide",
    cycle: "2027 intake",
    status: "watch",
    url: "https://jobs.bt.com/job/Register-Your-Interest-Grads-%26-Apprenticeships-2027/62260-en_GB/",
    evidence: "官方 2027 Early Careers 登记岗位 2026-08-26 上线",
    fit: "Business Operations · Data & AI · Project Management",
    workAuthorization: "须在项目全程具备英国全职工作权利",
    verifiedAt: "2026-09-01",
  },
  {
    id: "uk-parliament-2027",
    company: "UK Parliament",
    country: "英国",
    title: "Houses of Parliament Graduate Development Programme",
    location: "London",
    cycle: "2027 intake",
    status: "watch",
    url: "https://www.parliament.uk/about/careers/graduate-programme/",
    evidence: "官方页面明确写明 2027 项目将在 2026 年秋季开放",
    fit: "Policy · Research · Operations · Public Affairs",
    workAuthorization: "国籍与工作权利条件以正式申请页为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "bank-of-england-2027",
    company: "Bank of England",
    country: "英国",
    title: "Graduate Development Programme 2027",
    location: "London / Leeds",
    cycle: "2027 intake",
    status: "watch",
    url: "https://www.bankofengland.co.uk/careers/future-talent/graduate-programme",
    evidence: "官方项目页支持登记 2027 opportunities，当前职位待开放",
    fit: "Economics · Data · Risk · Operations",
    workAuthorization: "具体项目的国籍、背景调查及担保要求需逐条核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "jlr-uk-2027",
    company: "JLR",
    country: "英国",
    title: "Data Analytics / Project Management Graduate 2027",
    location: "United Kingdom",
    cycle: "September 2027 start",
    status: "opening_soon",
    opensOn: "2027-01-01",
    url: "https://careers.jaguarlandrover.com/early-careers/graduates",
    evidence: "官方页面列明 Data Analytics、Project Management 等项目 2027 年 1 月开放",
    fit: "Data · Project Management · Operations",
    workAuthorization: "官方明确 Graduate Programme 不提供签证担保",
    verifiedAt: "2026-09-01",
  },
  {
    id: "unilever-uk-uflp-2027",
    company: "Unilever",
    country: "英国",
    title: "Unilever Future Leaders Programme",
    location: "United Kingdom / Ireland",
    cycle: "2027 watch",
    status: "watch",
    url: "https://careers.unilever.com/en/united-kingdom-and-ireland",
    evidence: "官方 UK&I Early Careers 页面持续列出 UFLP Graduate 路径",
    fit: "Marketing · Commercial · Supply Chain · Finance",
    workAuthorization: "具体批次开放与工作权利条件需回到 vacancy 核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "mclaren-racing-engineering-2027",
    company: "McLaren Racing",
    country: "英国",
    title: "Engineering Graduate Programme",
    location: "Woking",
    cycle: "September 2027 start",
    status: "open",
    deadline: "2026-10-07",
    url: "https://jobs.smartrecruiters.com/McLarenRacingLtd1/744000146035097-engineering-graduate",
    evidence: "官方招聘页已开放，2026-10-07 截止",
    fit: "Engineering · Data · Performance · Operations",
    workAuthorization: "英国工作权利与现场工作要求以申请表为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "blackrock-ft-analyst-2027",
    company: "BlackRock",
    country: "英国",
    title: "2027 Full-Time Analyst Program — EMEA",
    location: "London / Edinburgh",
    cycle: "August 2027 start",
    status: "open",
    deadline: "2026-09-30",
    url: "https://careers.blackrock.com/job/london/2027-full-time-analyst-program-emea/45831/97150826656",
    evidence: "官方岗位可申请，London / Edinburgh 申请截止 2026-09-30",
    fit: "Investment · Analytics · Technology · Client Solutions",
    workAuthorization: "工作权利与签证支持因地点和业务线而异，须在申请流程核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "blackrock-client-product-2027",
    company: "BlackRock",
    country: "英国",
    title: "Client & Product Graduate Rotational Program — EMEA",
    location: "London",
    cycle: "2027 intake",
    status: "open",
    deadline: "2026-09-30",
    url: "https://careers.blackrock.com/en/job/london/2027-client-and-product-graduate-rotational-program-emea/45831/97150826688",
    evidence: "官方岗位可申请，London 申请截止 2026-09-30",
    fit: "Product · Client Strategy · Markets · Analytics",
    workAuthorization: "工作权利与签证支持须按具体申请地点核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "cci-commodities-2027",
    company: "Castleton Commodities International",
    country: "英国",
    title: "Commodities Trading Rotational Analyst Graduate Programme",
    location: "London",
    cycle: "2027 start",
    status: "open",
    deadline: "2026-09-22",
    url: "https://osv-cci.wd1.myworkdayjobs.com/en-US/CCICareers/job/Commodities-Trading-Rotational-Analyst-Graduate-Programme--2027-Start-_R1334-1",
    evidence: "官方 Workday 岗位可申请，2026-09-22 12:00 BST 截止",
    fit: "Trading · Risk · Research · Data",
    workAuthorization: "官方岗位未公开承诺签证支持，申请前需确认英国工作资格",
    verifiedAt: "2026-09-01",
  },
  {
    id: "marshall-wace-bizops-2027",
    company: "Marshall Wace",
    country: "英国",
    title: "Business Operations Graduate Programme",
    location: "London",
    cycle: "September 2027 start",
    status: "open",
    url: "https://www.mwam.com/bizops-graduate-programme/",
    evidence: "官方项目页显示 Apply for September 2027 Now",
    fit: "Operations · Fund Accounting · Data · Technology",
    workAuthorization: "签证与英国工作权利要求未在项目页明确，需向招聘团队核验",
    verifiedAt: "2026-09-01",
  },
  {
    id: "kpmg-uk-2027",
    company: "KPMG UK",
    country: "英国",
    title: "Graduate Programmes 2027 — Talent Community",
    location: "United Kingdom",
    cycle: "2027 intake",
    status: "watch",
    url: "https://www.kpmgcareers.co.uk/student-talent-community/",
    evidence: "官方 Talent Community 提供 2027 Graduate 开放提醒，具体 vacancy 待上线",
    fit: "Audit · Consulting · Tax · Technology",
    workAuthorization: "担保政策依具体项目和地点判断，不能由 Talent Community 推断",
    verifiedAt: "2026-09-01",
  },
  {
    id: "hsbc-uk-graduate-programmes",
    company: "HSBC",
    country: "英国",
    title: "UK Graduate Programmes",
    location: "United Kingdom",
    cycle: "Rolling cohorts",
    status: "watch",
    url: "https://www.hsbc.com/careers/students-and-graduates/graduate-opportunities",
    evidence: "官方 Graduate Programme 集合页持续列出 UK 路径，需逐项核验当前批次",
    fit: "Banking · Markets · Risk · Technology",
    workAuthorization: "不同项目资格和签证条件不同，以具体 vacancy 为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "civil-service-fast-stream-2027",
    company: "UK Civil Service",
    country: "英国",
    title: "Civil Service Fast Stream 2027",
    location: "UK-wide",
    cycle: "2027 intake watch",
    status: "watch",
    url: "https://www.civil-service-careers.gov.uk/fast-stream/",
    evidence: "官方页显示上一批次已关闭；保留官方入口追踪下一轮开放，不标记为在招",
    fit: "Policy · Analysis · Digital · Operations",
    workAuthorization: "须满足各 Fast Stream 路径的国籍与工作权利要求",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-customer-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Technology & Transformation — Customer New Grad 2027",
    location: "Toronto / Calgary / Halifax / Montréal / Vancouver",
    cycle: "Fall 2027",
    status: "open",
    deadline: "2026-09-18",
    url: "https://careers.deloitte.ca/job/Toronto%2C-ON-Technology-%26-Transformation-Customer-New-Grad-2027-Multiple-Locations-ON-M5H-0A9/134466-en_US/",
    evidence: "官方岗位 2026-08-20 上线，2026-09-18 截止",
    fit: "Customer · Product · Marketing · Commerce",
    workAuthorization: "岗位要求在加拿大合法工作；未承诺移民或工签支持",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-engineering-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Tech & Transformation — Engineering New Grad 2027",
    location: "Toronto / Montréal / Ottawa",
    cycle: "Fall 2027",
    status: "open",
    deadline: "2026-09-18",
    url: "https://careers.deloitte.ca/job/Tech-%26-Transformation-Engineering-New-Grad-2027-Multiple-Locations/134767-en_US/",
    evidence: "官方岗位 2026-08-20 上线，2026-09-18 截止",
    fit: "Technology · Engineering · Business Transformation",
    workAuthorization: "须在加拿大合法工作；Ottawa 岗位可能需要安全许可",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-deals-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Deal Transformation & Post Merger Integration New Grad",
    location: "Toronto / Montréal / Calgary / Vancouver",
    cycle: "Winter / Fall 2027",
    status: "open",
    deadline: "2026-09-18",
    url: "https://careers.deloitte.ca/job/Toronto%2C-ON-AnalystConsultant%2C-Deal-Transformation-%26-Post-Merger-Integration-New-Grad-2027-Multiple-Locations-ON-M5H-0A9/134482-en_US/",
    evidence: "官方岗位 2026-08-19 上线，2026-09-18 截止",
    fit: "Strategy · Operations · Transformation",
    workAuthorization: "岗位要求满足加拿大工作资格；魁北克岗位有语言条件",
    verifiedAt: "2026-09-01",
  },
  {
    id: "deloitte-ca-tax-2027",
    company: "Deloitte Canada",
    country: "加拿大",
    title: "Tax Analyst — New Grad 2027",
    location: "Multiple Canadian cities",
    cycle: "2027 intake",
    status: "open",
    deadline: "2026-09-13",
    url: "https://careers.deloitte.ca/job/Tax-%26-Legal-Tax-Analyst-New-Grad-2027-Multiple-Locations/134593-en_US/",
    evidence: "官方岗位 2026-08-17 上线；各地区 9 月 13 日至 10 月 4 日截止",
    fit: "Tax · Finance · Analysis",
    workAuthorization: "需满足加拿大工作资格并核验 CPA 先修要求",
    verifiedAt: "2026-09-01",
  },
  {
    id: "scotiabank-ib-vancouver-2027",
    company: "Scotiabank",
    country: "加拿大",
    title: "Investment Banking Analyst — New Grad",
    location: "Vancouver",
    cycle: "August 2027 start",
    status: "open",
    url: "https://jobs.scotiabank.com/job/Vancouver-GBM-Investment-Banking-Analyst-%28Vancouver%29-New-Grad-BC/604770517/",
    evidence: "官方 New Grad 岗位页在线，要求 2027 年春季前完成学位",
    fit: "Investment Banking · Finance · Research",
    workAuthorization: "加拿大工作资格与具体筛选条件以申请页为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "scotiabank-wealth-edmonton-2027",
    company: "Scotiabank",
    country: "加拿大",
    title: "Wealth Management Associate Program",
    location: "Edmonton",
    cycle: "January 2027 start",
    status: "open",
    url: "https://jobs.scotiabank.com/job/Edmonton-Wealth-Management-Associate-Program-Scotia-Jarislowsky-Fraser-%28January-2027%29-Edmonton-AB/603122917/",
    evidence: "官方 New Graduate 项目页在线，接受 2027 年 1 月前毕业或近期毕业生",
    fit: "Wealth · Client Service · Financial Planning",
    workAuthorization: "加拿大工作资格与牌照要求以申请页为准",
    verifiedAt: "2026-09-01",
  },
  {
    id: "capital-one-ca-strategy-2027",
    company: "Capital One Canada",
    country: "加拿大",
    title: "Associate, Strategy Analyst — New Grad 2027",
    location: "Toronto",
    cycle: "2027 intake",
    status: "open",
    url: "https://www.capitalonecareers.ca/en/job/toronto/associate-strategy-analyst-new-grad-2027/1733/95057302624",
    evidence: "官方岗位 2026-08-04 上线，当前页面可申请",
    fit: "Strategy · Analytics · Product · Business Operations",
    workAuthorization: "需提交简历与非正式成绩单；工作许可支持未在页面公开确认",
    verifiedAt: "2026-09-01",
  },
  {
    id: "capital-one-ca-process-2027",
    company: "Capital One Canada",
    country: "加拿大",
    title: "Associate, Process Management — New Grad 2027",
    location: "Toronto",
    cycle: "2027 intake",
    status: "open",
    url: "https://www.capitalonecareers.ca/search-jobs?acm=ALL&alrpm=ALL&ascf=%5B%7B%22key%22%3A%22custom_fields.gradfacet%22%2C%22value%22%3A%22Students+%26+Grads%22%7D%5D",
    evidence: "官方 Students & Grads 页面列出该 New Grad 2027 岗位",
    fit: "Process Management · Operations · Project Delivery",
    workAuthorization: "工作许可支持未在公开列表确认，申请前需查看完整 JD",
    verifiedAt: "2026-09-01",
  },
  {
    id: "trafigura-calgary-2027",
    company: "Trafigura",
    country: "加拿大",
    title: "Calgary Development Graduate Programme",
    location: "Calgary",
    cycle: "October 2027 start",
    status: "open",
    deadline: "2026-09-21",
    url: "https://trafigura.wd3.myworkdayjobs.com/en-US/TrafiguraCareerSite/job/Calgary-Canada/Calgary-Development-Graduate-Programme_R-018524",
    evidence: "官方 Workday 岗位显示 2026-09-21 截止",
    fit: "Operations · Risk · Supply Chain",
    workAuthorization: "项目强调全球流动性；工作许可仍需向雇主确认",
    verifiedAt: "2026-09-01",
  },
  {
    id: "rogers-cpa-2027",
    company: "Rogers Communications",
    country: "加拿大",
    title: "CPA Rotational Program — Financial Analyst",
    location: "Toronto",
    cycle: "September 2027 start",
    status: "open",
    url: "https://jobs.rogers.com/job/Toronto-Financial-Analyst-ON/1417798200/",
    evidence: "官方岗位页已上线，明确为 2027 CPA Rotational Program",
    fit: "Finance · Analysis · Rotational",
    workAuthorization: "申请需提交大学成绩单；工作资格看岗位申请表",
    verifiedAt: "2026-09-01",
  },
  {
    id: "rbc-rotational-programs",
    company: "RBC",
    country: "加拿大",
    title: "New Graduate & Rotational Programs",
    location: "Canada",
    cycle: "Rolling cohorts",
    status: "watch",
    url: "https://jobs.rbc.com/ca/en/students-graduates-new-graduate-rotational-programs/",
    evidence: "官方项目集合页在线，包含 Capital Markets、CPA、Analyst 等路径",
    fit: "Banking · Finance · Technology · Leadership",
    workAuthorization: "各项目资格不同，必须在具体 vacancy 核验",
    verifiedAt: "2026-09-01",
  },
];
