export type TargetCountry = "中国" | "英国" | "加拿大";

export type JobSource = {
  company: string;
  displayName?: string;
  country: TargetCountry;
  careersUrl: string;
  provider: "greenhouse" | "lever" | "ashby" | "tencent" | "official";
  group?: "在华外企";
  token?: string;
  sponsorQuery?: string;
};

export const jobSources: JobSource[] = [
  { company: "TikTok / ByteDance", displayName: "字节跳动 TikTok / ByteDance", country: "中国", careersUrl: "https://jobs.bytedance.com/zh/", provider: "official" },
  { company: "Alibaba", displayName: "阿里巴巴 Alibaba", country: "中国", careersUrl: "https://talent.alibaba.com/", provider: "official" },
  { company: "Ant Group", displayName: "蚂蚁集团 Ant Group", country: "中国", careersUrl: "https://talent.antgroup.com/", provider: "official" },
  { company: "Meituan", displayName: "美团 Meituan", country: "中国", careersUrl: "https://zhaopin.meituan.com/", provider: "official" },
  { company: "Tencent", displayName: "腾讯 Tencent", country: "中国", careersUrl: "https://join.qq.com/", provider: "tencent" },
  { company: "JD.com", displayName: "京东 JD.com", country: "中国", careersUrl: "https://zhaopin.jd.com/", provider: "official" },
  { company: "PDD / Temu", displayName: "拼多多 PDD / Temu", country: "中国", careersUrl: "https://careers.pddglobalhr.com/", provider: "official" },
  { company: "Xiaohongshu", displayName: "小红书 Xiaohongshu", country: "中国", careersUrl: "https://job.xiaohongshu.com/", provider: "official" },
  { company: "Kuaishou", displayName: "快手 Kuaishou", country: "中国", careersUrl: "https://zhaopin.kuaishou.cn/", provider: "official" },
  { company: "Bilibili", displayName: "哔哩哔哩 Bilibili", country: "中国", careersUrl: "https://jobs.bilibili.com/", provider: "official" },
  { company: "Baidu", displayName: "百度 Baidu", country: "中国", careersUrl: "https://talent.baidu.com/", provider: "official" },
  { company: "Trip.com Group", displayName: "携程 Trip.com Group", country: "中国", careersUrl: "https://careers.trip.com/", provider: "official" },
  { company: "NetEase", displayName: "网易 NetEase", country: "中国", careersUrl: "https://campus.163.com/", provider: "official" },
  { company: "DiDi", displayName: "滴滴 DiDi", country: "中国", careersUrl: "https://talent.didiglobal.com/", provider: "official" },
  { company: "Xiaomi", displayName: "小米 Xiaomi", country: "中国", careersUrl: "https://hr.xiaomi.com/", provider: "official" },
  { company: "Huawei", displayName: "华为 Huawei", country: "中国", careersUrl: "https://career.huawei.com/", provider: "official" },
  { company: "OPPO", country: "中国", careersUrl: "https://careers.oppo.com/", provider: "official" },
  { company: "vivo", country: "中国", careersUrl: "https://hr.vivo.com/", provider: "official" },
  { company: "iQIYI", displayName: "爱奇艺 iQIYI", country: "中国", careersUrl: "https://zhaopin.iqiyi.com/", provider: "official" },
  { company: "Tencent Music", displayName: "腾讯音乐 Tencent Music", country: "中国", careersUrl: "https://join.tencentmusic.com/", provider: "official" },
  { company: "Weibo", displayName: "微博 Weibo", country: "中国", careersUrl: "https://career.sina.com.cn/", provider: "official" },
  { company: "Zhihu", displayName: "知乎 Zhihu", country: "中国", careersUrl: "https://app.mokahr.com/campus-recruitment/zhihu/38650", provider: "official" },
  { company: "Dewu / Poizon", displayName: "得物 Dewu / Poizon", country: "中国", careersUrl: "https://campus.dewu.com/", provider: "official" },
  { company: "BOSS Zhipin", displayName: "BOSS直聘 BOSS Zhipin", country: "中国", careersUrl: "https://www.zhipin.com/gongsi/job/", provider: "official" },
  { company: "Kingsoft", displayName: "金山 Kingsoft", country: "中国", careersUrl: "https://campus.kingsoft.com/", provider: "official" },
  { company: "360", country: "中国", careersUrl: "https://campus.360.cn/", provider: "official" },
  { company: "Lenovo", displayName: "联想 Lenovo", country: "中国", careersUrl: "https://jobs.lenovo.com/", provider: "official" },
  { company: "Keep", country: "中国", careersUrl: "https://keep.jobs.feishu.cn/", provider: "official" },
  { company: "Soul", country: "中国", careersUrl: "https://soul.jobs.feishu.cn/", provider: "official" },
  { company: "Perfect World", displayName: "完美世界 Perfect World", country: "中国", careersUrl: "https://recruit.wanmei.com/", provider: "official" },

  // 在中国大陆设有团队或长期招聘入口的热门外企。
  { company: "宝洁 P&G", country: "中国", careersUrl: "https://www.pgcareers.com/cn/zh", provider: "official", group: "在华外企" },
  { company: "Shopee", country: "中国", careersUrl: "https://careers.shopee.cn/", provider: "official", group: "在华外企" },
  { company: "亚马逊 Amazon", country: "中国", careersUrl: "https://www.amazon.jobs/en/search?base_query=&loc_query=China", provider: "official", group: "在华外企" },
  { company: "苹果 Apple", country: "中国", careersUrl: "https://jobs.apple.com/zh-cn/search?location=china-CHNC", provider: "official", group: "在华外企" },
  { company: "微软 Microsoft", country: "中国", careersUrl: "https://careers.microsoft.com/v2/global/en/locations/gcr.html", provider: "official", group: "在华外企" },
  { company: "谷歌 Google", country: "中国", careersUrl: "https://www.google.com/about/careers/applications/jobs/results/?location=China", provider: "official", group: "在华外企" },
  { company: "特斯拉 Tesla", country: "中国", careersUrl: "https://www.tesla.cn/careers", provider: "official", group: "在华外企" },
  { company: "英伟达 NVIDIA", country: "中国", careersUrl: "https://www.nvidia.com/en-us/about-nvidia/careers/", provider: "official", group: "在华外企" },
  { company: "英特尔 Intel", country: "中国", careersUrl: "https://www.intel.com/content/www/us/en/jobs/locations.html", provider: "official", group: "在华外企" },
  { company: "IBM", country: "中国", careersUrl: "https://www.ibm.com/careers/locations", provider: "official", group: "在华外企" },
  { company: "SAP", country: "中国", careersUrl: "https://jobs.sap.com/go/SAP-Jobs-in-China/881201/", provider: "official", group: "在华外企" },
  { company: "思科 Cisco", country: "中国", careersUrl: "https://jobs.cisco.com/jobs/SearchJobs/", provider: "official", group: "在华外企" },
  { company: "戴尔科技 Dell Technologies", country: "中国", careersUrl: "https://jobs.dell.com/en/location/china-jobs/375/1814991/2", provider: "official", group: "在华外企" },
  { company: "博世 Bosch", country: "中国", careersUrl: "https://www.bosch.com.cn/careers/", provider: "official", group: "在华外企" },
  { company: "西门子 Siemens", country: "中国", careersUrl: "https://www.siemens.com/zh-cn/company/jobs/", provider: "official", group: "在华外企" },
  { company: "欧莱雅 L'Oréal", country: "中国", careersUrl: "https://careers.loreal.com/zh_CN/content/Home", provider: "official", group: "在华外企" },
  { company: "联合利华 Unilever", country: "中国", careersUrl: "https://careers.unilever.com/en/china", provider: "official", group: "在华外企" },
  { company: "耐克 Nike", country: "中国", careersUrl: "https://careers.nike.com/zh-cn/", provider: "official", group: "在华外企" },
  { company: "宜家 IKEA", country: "中国", careersUrl: "https://jobs.ikea.com/en/search-jobs/China/22908/2/1814991/35/105", provider: "official", group: "在华外企" },
  { company: "玛氏 Mars", country: "中国", careersUrl: "https://careers.mars.com/cn/zh", provider: "official", group: "在华外企" },

  { company: "AlphaSights", country: "英国", careersUrl: "https://www.alphasights.com/careers/", provider: "greenhouse", token: "alphasights", sponsorQuery: "AlphaSights Ltd" },
  { company: "Monzo", country: "英国", careersUrl: "https://monzo.com/careers", provider: "greenhouse", token: "monzo", sponsorQuery: "Monzo Bank Limited" },
  { company: "TrueLayer", country: "英国", careersUrl: "https://truelayer.com/careers/", provider: "greenhouse", token: "truelayer", sponsorQuery: "TrueLayer Limited" },
  { company: "Coinbase", country: "英国", careersUrl: "https://www.coinbase.com/careers", provider: "greenhouse", token: "coinbase", sponsorQuery: "Coinbase UK, Ltd" },
  { company: "Zopa", country: "英国", careersUrl: "https://www.zopa.com/careers", provider: "lever", token: "zopa", sponsorQuery: "Zopa Bank Limited" },
  { company: "OpenPayd", country: "英国", careersUrl: "https://www.openpayd.com/company/careers", provider: "lever", token: "OpenPayd", sponsorQuery: "OpenPayd Services Limited" },
  { company: "Recognise Bank", country: "英国", careersUrl: "https://www.recognisebank.co.uk/careers/", provider: "lever", token: "recognisebank", sponsorQuery: "Recognise Bank Limited" },
  { company: "Apollo Research", country: "英国", careersUrl: "https://www.apolloresearch.ai/careers", provider: "lever", token: "apolloresearch", sponsorQuery: "Apollo Research Limited" },
  { company: "Wise", country: "英国", careersUrl: "https://www.wise.jobs/", provider: "official", sponsorQuery: "Wise Payments Limited" },
  { company: "Revolut", country: "英国", careersUrl: "https://www.revolut.com/careers/", provider: "official", sponsorQuery: "Revolut Ltd" },
  { company: "Checkout.com", country: "英国", careersUrl: "https://www.checkout.com/careers", provider: "official", sponsorQuery: "Checkout Ltd" },
  { company: "Starling Bank", country: "英国", careersUrl: "https://www.starlingbank.com/careers/", provider: "official", sponsorQuery: "Starling Bank Limited" },
  { company: "Deloitte", country: "英国", careersUrl: "https://www.deloitte.com/uk/en/careers.html", provider: "official", sponsorQuery: "Deloitte LLP" },
  { company: "GoCardless", country: "英国", careersUrl: "https://gocardless.com/about/careers/", provider: "greenhouse", token: "gocardless", sponsorQuery: "GoCardless Ltd" },
  { company: "Tide", country: "英国", careersUrl: "https://www.tide.co/careers/", provider: "greenhouse", token: "tide", sponsorQuery: "Tide Platform Limited" },
  { company: "Stripe", country: "英国", careersUrl: "https://stripe.com/jobs", provider: "greenhouse", token: "stripe", sponsorQuery: "Stripe Payments UK Ltd" },
  { company: "SumUp", country: "英国", careersUrl: "https://www.sumup.com/careers/", provider: "greenhouse", token: "sumup", sponsorQuery: "SumUp Payments Limited" },
  { company: "ClearBank", country: "英国", careersUrl: "https://clear.bank/careers", provider: "ashby", token: "clearbank", sponsorQuery: "ClearBank Limited" },
  { company: "OakNorth", country: "英国", careersUrl: "https://www.oaknorth.co.uk/careers/", provider: "ashby", token: "oaknorth", sponsorQuery: "OakNorth Bank plc" },
  { company: "Lendable", country: "英国", careersUrl: "https://www.lendable.co.uk/careers", provider: "ashby", token: "lendable", sponsorQuery: "Lendable Ltd" },
  { company: "Thought Machine", country: "英国", careersUrl: "https://www.thoughtmachine.net/careers", provider: "ashby", token: "thought-machine", sponsorQuery: "Thought Machine Group Limited" },
  { company: "Barclays", country: "英国", careersUrl: "https://search.jobs.barclays/", provider: "official", sponsorQuery: "Barclays Bank PLC" },
  { company: "HSBC", country: "英国", careersUrl: "https://www.hsbc.com/careers", provider: "official", sponsorQuery: "HSBC UK Bank plc" },
  { company: "Lloyds Banking Group", country: "英国", careersUrl: "https://www.lloydsbankinggroup.com/careers.html", provider: "official", sponsorQuery: "Lloyds Bank plc" },
  { company: "NatWest Group", country: "英国", careersUrl: "https://jobs.natwestgroup.com/", provider: "official", sponsorQuery: "National Westminster Bank Plc" },
  { company: "Standard Chartered", country: "英国", careersUrl: "https://www.sc.com/en/global-careers/", provider: "official", sponsorQuery: "Standard Chartered Bank" },
  { company: "Bank of England", country: "英国", careersUrl: "https://www.bankofengland.co.uk/careers", provider: "official", sponsorQuery: "Bank of England" },
  { company: "J.P. Morgan", country: "英国", careersUrl: "https://careers.jpmorgan.com/", provider: "official", sponsorQuery: "J.P. Morgan Securities plc" },
  { company: "Goldman Sachs", country: "英国", careersUrl: "https://www.goldmansachs.com/careers/", provider: "official", sponsorQuery: "Goldman Sachs International" },
  { company: "Morgan Stanley", country: "英国", careersUrl: "https://www.morganstanley.com/people-opportunities/students-graduates", provider: "official", sponsorQuery: "Morgan Stanley & Co. International plc" },
  { company: "BlackRock", country: "英国", careersUrl: "https://careers.blackrock.com/", provider: "official", sponsorQuery: "BlackRock Investment Management (UK) Limited" },
  { company: "Bloomberg", country: "英国", careersUrl: "https://www.bloomberg.com/company/careers/", provider: "official", sponsorQuery: "Bloomberg L.P." },
  { company: "Visa", country: "英国", careersUrl: "https://corporate.visa.com/en/careers.html", provider: "official", sponsorQuery: "Visa Europe Limited" },
  { company: "Mastercard", country: "英国", careersUrl: "https://careers.mastercard.com/", provider: "official", sponsorQuery: "Mastercard UK Management Services Limited" },
  { company: "Fidelity International", country: "英国", careersUrl: "https://careers.fidelityinternational.com/", provider: "official", sponsorQuery: "FIL Investment Services (UK) Limited" },
  { company: "Schroders", country: "英国", careersUrl: "https://www.schroders.com/en/global/careers/", provider: "official", sponsorQuery: "Schroder Investment Management Limited" },

  { company: "StackAdapt", country: "加拿大", careersUrl: "https://www.stackadapt.com/careers", provider: "greenhouse", token: "stackadapt" },
  { company: "Hootsuite", country: "加拿大", careersUrl: "https://careers.hootsuite.com/", provider: "greenhouse", token: "hootsuite" },
  { company: "DoorDash Canada", country: "加拿大", careersUrl: "https://careersatdoordash.com/", provider: "greenhouse", token: "doordashcanada" },
  { company: "Faire", country: "加拿大", careersUrl: "https://www.faire.com/careers", provider: "greenhouse", token: "faire" },
  { company: "Shopify", country: "加拿大", careersUrl: "https://www.shopify.com/careers", provider: "official" },
  { company: "Wealthsimple", country: "加拿大", careersUrl: "https://www.wealthsimple.com/en-ca/careers", provider: "ashby", token: "wealthsimple" },
  { company: "RBC", country: "加拿大", careersUrl: "https://jobs.rbc.com/ca/en", provider: "official" },
  { company: "TD", country: "加拿大", careersUrl: "https://jobs.td.com/en-CA/", provider: "official" },
  { company: "BMO", country: "加拿大", careersUrl: "https://jobs.bmo.com/ca/en", provider: "official" },
  { company: "Scotiabank", country: "加拿大", careersUrl: "https://jobs.scotiabank.com/", provider: "official" },
  { company: "CIBC", country: "加拿大", careersUrl: "https://www.cibc.com/en/about-cibc/careers.html", provider: "official" },
  { company: "Clio", country: "加拿大", careersUrl: "https://www.clio.com/about/careers/", provider: "official" },
  { company: "PwC Canada", country: "加拿大", careersUrl: "https://www.pwc.com/ca/en/careers.html", provider: "official" },
  { company: "KOHO", country: "加拿大", careersUrl: "https://www.koho.ca/careers/", provider: "ashby", token: "koho" },
  { company: "Float", country: "加拿大", careersUrl: "https://floatfinancial.com/careers", provider: "ashby", token: "float" },
  { company: "Neo Financial", country: "加拿大", careersUrl: "https://www.neofinancial.com/careers", provider: "ashby", token: "neofinancial" },
  { company: "EQ Bank", country: "加拿大", careersUrl: "https://eqb.inflightcloud.com/careerpage", provider: "lever", token: "eqbank" },
  { company: "National Bank of Canada", country: "加拿大", careersUrl: "https://jobs.nbc.ca/", provider: "official" },
  { company: "Desjardins", country: "加拿大", careersUrl: "https://www.desjardins.com/ca/careers/", provider: "official" },
  { company: "Tangerine", country: "加拿大", careersUrl: "https://jobs.scotiabank.com/Tangerine/", provider: "official" },
  { company: "Manulife", country: "加拿大", careersUrl: "https://careers.manulife.com/", provider: "official" },
  { company: "Sun Life", country: "加拿大", careersUrl: "https://sunlife.wd3.myworkdayjobs.com/", provider: "official" },
  { company: "Canada Life", country: "加拿大", careersUrl: "https://www.canadalife.com/about-us/careers.html", provider: "official" },
  { company: "CPP Investments", country: "加拿大", careersUrl: "https://www.cppinvestments.com/careers/", provider: "official" },
  { company: "OMERS", country: "加拿大", careersUrl: "https://www.omers.com/careers", provider: "official" },
  { company: "Ontario Teachers' Pension Plan", country: "加拿大", careersUrl: "https://www.otpp.com/en-ca/about-us/careers/", provider: "official" },
  { company: "Intact Financial", country: "加拿大", careersUrl: "https://careers.intactfc.com/", provider: "official" },
  { company: "TMX Group", country: "加拿大", careersUrl: "https://www.tmx.com/careers", provider: "official" },
  { company: "Interac", country: "加拿大", careersUrl: "https://www.interac.ca/en/careers/", provider: "official" },
  { company: "Questrade", country: "加拿大", careersUrl: "https://www.questrade.com/about-us/careers", provider: "official" },
  { company: "Payments Canada", country: "加拿大", careersUrl: "https://www.payments.ca/about-us/careers", provider: "official" },
  { company: "Visa Canada", country: "加拿大", careersUrl: "https://corporate.visa.com/en/careers.html", provider: "official" },
  { company: "Mastercard Canada", country: "加拿大", careersUrl: "https://careers.mastercard.com/", provider: "official" },
  { company: "1Password", country: "加拿大", careersUrl: "https://1password.com/jobs/", provider: "ashby", token: "1password" },
];

export const liveSourceCount = jobSources.filter((source) => source.provider !== "official").length;
